### ISSUE TITLE
🎈 Roadmap / Suggestions

### ISSUE THREAD

**Issue by kangarko** [kangarko/Confiscate#9]
This is a list of features to be considered and added in the next release(s).

## Top Priority
- [ ] Confiscate/Ignore certain lore/name, https://github.com/kangarko/Confiscate/issues/35
- [ ] Rewrite to not use outdated PowerNBT, https://github.com/kangarko/Confiscate/issues/86

## High priority
- [ ] Support for BossShop and TradeMe plugins.
- [ ] Scan Armor slot as well
- [ ] MySQL instead of a physical chest room
- [ ] Room integrity awareness - possible removal of old chests
- [ ] Log cleaning
- [ ] Buy limits with economy
- [ ] Confiscating Attributes

## Normal priority
- Improve log entries: https://github.com/kangarko/Confiscate/issues/102 and https://github.com/kangarko/Confiscate/issues/103
- https://github.com/kangarko/Confiscate/issues/101
- [ ] Items with an specific name will disappear if players do not have a permission.
- [ ] Per-World config
- [ ] Redstone item restrictions (hoppers, droppers, dispensors etc.) per-chunk
- [ ] Support for the mcMMO temporary enchantments 
- [ ] Group limits for block confiscation

## Add more dupe/exploit checks
- [ ] End and Nether portal duping methods.
- [ ] Oversized Chunk Saving exploit with signs and books.
- [ ] Preventing pistons from being able to glitch minecarts inside solid blocks.
- [ ] Breaks nether portals that are blocked up are used to trap other players upon login.
- [ ] Preventing players from using dispensers/droppers from breaking end portals.
- [ ] Also, add checks to furnaces/hoppers and other places where you can store an item and it doesn't get detected
- [ ] Adding a way to hide commands not via permissions at a packet level, so hack clients and other regular players cannot view what plugins you have (via auto tab completion and other) without specific permission to do so.
This may not fall under confiscate which I understand but many other plugins that had this have been abandoned, so I think this is probably the best place to go.
- [ ] Making it so when different ranks of visibility are setup via a vanish plugin, the lower-ranked staff can't see the higher-ranked staff commands. For example, the rank helper (lowest) wouldn't be able to see moderators' commands, but the moderator can see helpers, but the moderator can't see owners. Like that.

**Feel free to comment below, but comments are cleaned regularly to keep this page clean.**

**Comment by DuckCraftPvP** [comment]
Can you update support for papi to support relational placeholders?

**Comment by kangarko** [comment]
This is not possible if you are browsing chests' content.

**Comment by DuckCraftPvP** [comment]
what?

**Comment by DuckCraftPvP** [comment]
omfg i keep posting on wrong wikis

**Comment by TheChampTF** [comment]
Suggestion, add Item Restrictions to e.g. limit use of hoppers, potions and so on for different worlds.

**Comment by kangarko** [comment]
How would you like them to be limited?

**Comment by TheChampTF** [comment]
Lets say e.g. allow use of 20 normal hoppers, and 10 hopper minecarts

**Comment by kangarko** [comment]
Hey, I am afraid this is impossible to track. Users can build hoppers all over the world, and other users can also manipulate with them. If Confiscate should keep trace of existing blocks, it would be flawed, because blocks can be destroyed in tens of ways we cannot see, for example third party plugins, or restored (e.g. LogBlock) which would cause bugs.

**Comment by TheChampTF** [comment]
Hmm, just thinking out. Limited amount pr. chunk/area sizes?

**Comment by kangarko** [comment]
Sounds good, I can do that!

**Comment by TheChampTF** [comment]
Of what I can see, it's already down the current one as it would limit un-needed items, just via chunks/area sizes.

**Comment by kangarko** [comment]
Sounds good, I will mark it down.

**Comment by x1p** [comment]
There is already a plugin to limit the amount of items per chunk. Its called clearlag.

**Comment by ArtNRG** [comment]
https://github.com/kangarko/Confiscate/issues/35#issuecomment-377194914

**Comment by kangarko** [comment]
We unfortunately had to put Confiscate on maintenance due to other, bigger projects.
